### ISSUE TITLE
MISLABELLING DRUGS TO PATIENT D:

### ISSUE THREAD

**Issue by bobotong** [Frikster/EDS_converter#7] opened 2016-12-19 19:29 UTC
![image](https://cloud.githubusercontent.com/assets/24418843/21326178/5d3e320a-c5de-11e6-941d-5a838d430713.png)

where the red highlight is.... that's actually the start of 019704A-

**Comment by bobotong** [comment] 2016-12-19 19:35
![image](https://cloud.githubusercontent.com/assets/24418843/21326352/1c1ee6ba-c5df-11e6-898c-153472bdb223.png)

and again here... red line and down belongs to 020101ABCDE

**Comment by bobotong** [comment] 2016-12-19 20:25
![image](https://cloud.githubusercontent.com/assets/24418843/21326509/dc8da6a2-c5df-11e6-9c33-6ac7e5263a75.png)

red line down belongs to 41001....

**Comment by Frikster** [comment] 2016-12-19 20:56
On it.

**Comment by Frikster** [comment] 2016-12-19 22:33
ok, it is a pretty obvious what the problem is. I thought all patient numbers have 6 digits immediately followed by a dash. 019704A- and 020101ABCDE both have six digits but the A precedes the dash. This is an easy fix and I just implemented the change

020101ABCDE presents an additional problem. I thought all patient numbers had a '-'.  I've made it more lenient such any value that has 6 figits preceding a non digit is a patient number. This seems overly lenient to me so please be vigilant. Though maybe it wont be. I actually cant think of a particular case where being this lenient will cause an issue.

I think by 41001 you meant 041001ABCD, which should also be fixed now. However, if there really are patient numbers that are nothing more than 5 digits we are in for a dusi.

**Closed as completed by Frikster** 2016-12-19 22:33 UTC
Labels: bug
